meta_product_name: "Hew to get muscles"
meta_title: "How to get muscles - HTGM"
meta_description: "belle description"
meta_image: "logo1.png" # should exist in `app/assets/images/`
twitter_account: "@how_to_get_muscles" # required for Twitter Cards
